# CI for pull requests
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle?learn=continuous_integration&learnProduct=actions
# Using gradle-build-action. See https://github.com/gradle/gradle-build-action

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LICENSE: ${{ secrets.LICENSE }} #unity 2019 license 
      LICENSE2: ${{ secrets.LICENSE2 }}
      LICENSE2020: ${{ secrets.LICENSE_2020 }}
      LICENSE2021: ${{ secrets.LICENSE_2021 }}
    strategy:
      matrix:
        unity-version: [ 2019.4.36f1 ] #,2020.3.30f1, 2021.2.14f1

    steps:


      - name: Checkout Passthrough Example
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      #https://github.com/marketplace/actions/setup-unity
      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-modules: android
          install-path: /opt/Unity/
      - name: list all files in unity install dir
        run: |
          echo $UNITY_PATH 
          find $UNITY_PATH 
      - name: list all files in unity install dir
        run: |
          find /opt/Unity/
      - name: write out license file 2019
        if: ${{ contains(matrix.unity-version,'2019') }}
        run: |
          echo -n -e "$LICENSE" > license.alf
          echo inside a multi-line script: $LICENSE
          wc -m license.alf
          ls -al *alf
      - name: write out license file 2020
        if: ${{ contains(matrix.unity-version,'2020') }}
        run: |
          echo -n -e "$LICENSE2020" > license.alf
          echo inside a multi-line script: $LICENSE2020
          wc -m license.alf
          ls -al *alf
      - name: write out license file 2021
        if: ${{ contains(matrix.unity-version,'2021') }}
        run: |
          echo -n -e "$LICENSE2021" > license.alf
          echo inside a multi-line script: $LICENSE2021
          wc -m license.alf
          ls -al *alf
      - name: alternate secret test
        run: |
          echo -n -e "$LICENSE2" > license2.alf
          echo inside a multi-line script: $LICENSE2
          wc -m license2.alf
          ls -al *alf
      #- run:
      #  name: accept licenses
      #  command: |
      #    echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager --licenses

      - name: list all files in build dir
        run: |
          find .