# CI for pull requests
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle?learn=continuous_integration&learnProduct=actions
# Using gradle-build-action. See https://github.com/gradle/gradle-build-action

name: CI

on:
  push:
    branches:
      - 'build'
      #- 'releases/**'
      #- '!releases/**-alpha'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LICENSE: ${{ secrets.LICENSE }} #unity 2019 license 
      LICENSE2: ${{ secrets.LICENSE2 }}
      LICENSE2020: ${{ secrets.LICENSE_2020 }}
      LICENSE2021: ${{ secrets.LICENSE_2021 }}
    strategy:
      matrix:
        unity-version-matrix: [ 2019.4.36f1 ] #,2020.3.30f1, 2021.2.14f1

    steps:
      - name: Checkout Passthrough Example
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      #https://github.com/marketplace/actions/setup-unity
      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-version: ${{ matrix.unity-version-matrix }}
          unity-modules: android
          install-path: /opt/Unity/
      - name: list all files in unity install dir
        run: |
          echo $UNITY_PATH 
          find $UNITY_PATH 
          find /home/runner/Unity
          echo $ANDROID_HOME
          echo $ANDROID_NDK_HOME
          echo $NDK_HOME
          ls ${{ matrix.unity-version-matrix }}
